export default {
    greeting: 'Welcome to Connections',
    tabTitle: 'Connections',
    loginFormTitle: 'CONNECTIONS',
    text1: 'Connect people with the benefits they need, with one simple application.',
    text2: 'Curious what you may qualify for?',
    screenerLink: 'Try our Quick Screener',
    userNameLink: 'User Name',
    passwordLink: 'Password',
    screenerUrl: 'http://oxcdemo.alluma.org/#/quick/intro',
    userNameUrl: 'https://cx-sb01-auth01.azurewebsites.net/Account/ForgotUsername?origin=',
    passwordUrl: 'https://cx-sb01-auth01.azurewebsites.net/Account/ForgotPassword?origin=',
    text: 'If you need a user name, contact your system administrator.',
    lastText: 'Interested in becoming a Connections user? Learn More',
    userNLabel: 'User name required',
    pLabel: 'Password required',
    forgotText: 'Forgot User Name or Password ?',
    loginBtnTitle: 'Log In',
    userNameIsRequired: 'The Username field is required.'
}